<?php

namespace App\Http\Controllers;

/**
 * The in-app teacher help guide: a simple, screenshot-led walkthrough of every
 * task a teacher does (log in, mark attendance, hand out books, back-fill, read
 * the reports). It lives behind EnsureTeacherAuthenticated, so only logged-in
 * teachers can reach it. The screenshots it shows are committed under
 * public/images/help and regenerated by tests/Browser/HelpScreenshotsCapture.php.
 */
class HelpController extends Controller
{
    public function index()
    {
        return view('help.index');
    }
}
